bot:
  username: RateYourDay
  token: ${BOT_TOKEN}
  aesKey: ${AES_KEY}
spring:
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      continue-on-error: true
